### PR TITLE
Reworked GitHub test

### PR DESCRIPTION
**Pull request by muffato**
Hi @ksenia-krasheninnikova 

I've managed to make the pipeline take remote files directly. This means that:

1. There is no need to download and unpack a tar.gz before running tests
2. The `test_github` profile now runs out of the box anywhere

The main things I had to change in the code are:

- Make sure all dependent files are properly marked as `file` in Nextflow and passed through channels. Nextflow takes care of the download if necessary
- 10X files now have to be passed explicitly 

I also removed some Busco log files leftover from some tests.

With that solved, we can then look at renaming the test profiles. Normally, `test`, `test_github` should be the one that works for everyone, incl. GitHub.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomeassembly/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by ksenia-krasheninnikova — COMMENTED** [review]
@muffato All looks good to me! Thank you for the updates.

Currently the difference between `test` and `test_github` profiles is that the second one has the special longranger configuration. However we don't really run polishing for testing on github and we won't need it in any foreseeable future. With that in mind we can get rid of `test_github` profile for now and run `test` profile on github. 
Do you have another renaming in mind?

**Comment by muffato** [comment]
There's one difference: `test` was using
```
hic_aligner: bwamem2
```
while `test_github` has:
```
hic_aligner: minimap2
```

**Comment by ksenia-krasheninnikova** [comment]
It has to be 

<pre>
hic_aligner: bwamem2
</pre>

in both. 

minimap2 option was implemented for extra big genomes - it has to be tested separately.

**Comment by muffato** [comment]
All done, then 👍🏼

**Review by ksenia-krasheninnikova — APPROVED** [review]
Looks good to me! Thanks.

**Pull request merged**
