### PR TITLE
Added the Martian template as an asset

### PR DESCRIPTION
**Pull request by muffato**
This PR is to make longranger work in LSF mode in the pipeline.
I haven't had any issue with my tests so far (the `test` profile of this pipeline). The only change I had to make was adding this template, which I guess you had uncommitted in your checkout

I'll leave this as a draft PR until we've confirmed it works for everyone

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomeassembly/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by priyanka-surana — COMMENTED** [review]
I ran the test with and without `jobmode lsf` for `longranger/align`, it runs successfully in both cases. But it takes much longer with `jobmode lsf`, this can be due to a large overhead when running for a small job.

**Comment by priyanka-surana** [comment]
@muffato Try adding `--jobmode=lsf` to `LONGRANGER_ALIGN` `ext.args` and running it.

**Comment by muffato** [comment]
In an interactive session with 12 cores:

- Vanilla checkout: 3m 5s
- With `--jobmode=lsf`: 4m 59s

At the last dev day, I did the same on a 16-core interactive session:

- by default: 4m 33s (why is that slower than on the 12 cores machine ? Perhaps other factors, like how busy the node is, maybe different CPU models)
- With `--jobmode=lsf`: 4m 42s

which shows how variable the runtime can be.

Overall, I'm not too troubled by the difference on this test dataset. I'm reinsured that I can see the jobs filling up `bjobs` when run in LSF jobmode.

**Review by priyanka-surana — APPROVED** [review]
Okay then. Looks good to merge.

**Pull request merged**
