### PR TITLE
Update paths for full test

### PR DESCRIPTION
**Pull request by ksenia-krasheninnikova**
Update the data location to make it accessible from nextflow tower

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/genomeassembly/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by gq1** [comment]
The new location should be fine for user `toldev` and other tol users to run the full tests.

There is one other file still in your person location, is it being used? 
https://github.com/sanger-tol/genomeassembly/blob/1aa5c6007e18047b6af25fb24821edfe51d5145b/assets/test_iyVesGerm1.yaml#L4

**Comment by ksenia-krasheninnikova** [comment]
@gq1 I copied the datasets for iyVesGerm1 and gfLaeSulp1 to the new location. They are both of a moderate size may be useful to have an extra dataset for testing ready for the tower.
Removed an extra test file as there is no need to keep it on github.

**Comment by gq1** [comment]
Do you want to merge now? And hope this time it will pass.

**Comment by gq1** [comment]
And now all your CI tests running on the large runner and it seems fine every time. Hope you can make the` organelles_on` work there next time.

**Comment by ksenia-krasheninnikova** [comment]
Merged into dev. Thanks @gq1

**Pull request merged**
